version: '3'

services:
  db:
    image: 'postgres'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - gembrg
  gem:
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_RELATIVE_URL_ROOT=${RAILS_RELATIVE_URL_ROOT}
      - POSTGRES_HOST_NAME=${POSTGRES_HOST_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    networks:
      - gembrg
    links:
      - db:pg
    volumes:
      - .:/active_record-journal

networks:
  gembrg: