# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  gem:
    docker:
      - image: cimg/ruby:2.7.0
        auth:
          username: $DOCKERHUB_ACCESS_USER
          password: $DOCKERHUB_ACCESS_TOKEN
        environment:
          RAILS_ENV: test
          RAILS_RELATIVE_URL_ROOT: '/home/circleci/project'
  postgresql:
    docker:
      - image: cimg/ruby:2.7.0
        auth:
          username: $DOCKERHUB_ACCESS_USER
          password: $DOCKERHUB_ACCESS_TOKEN
        environment:
          RAILS_ENV: test
          POSTGRES_HOST_NAME: localhost
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          RAILS_RELATIVE_URL_ROOT: '/home/circleci/project'
      - image: cimg/postgres:14.0
        auth:
          username: $DOCKERHUB_ACCESS_USER
          password: $DOCKERHUB_ACCESS_TOKEN
        environment:
          POSTGRES_DB: $POSTGRES_DB
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD

commands:
  dependencies:
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          name: Install system dependencies
          command: sudo apt install -y libpq-dev sqlite3 libsqlite3-dev
      - run:
          name: Install gem dependencies
          command: bundle install
  rubocop:
    steps:
      - run:
          name: Rubocop
          command: bundle exec rubocop
  rspec:
    steps:
      - run:
          name: Run Specs
          command: bundle exec rspec
      - persist_to_workspace:
          root: coverage
          paths:
            - .last_run.json
  simplecov:
    steps:
      - attach_workspace:
          at: coverage
      - run: chmod +x .circleci/check_converage.rb
      - run: ./.circleci/check_converage.rb

jobs:
  build:
    description: 'Build gem dependencies'
    executor: gem
    steps:
      - dependencies
  linter:
    description: 'Rubocop'
    executor: gem
    steps:
      - dependencies
      - rubocop
  specs:
    description: 'Run specs'
    parameters:
      db:
        type: string
      executor:
        type: string
    executor: << parameters.executor >>
    steps:
      - dependencies
      - rspec
    environment:
      DB_CONFIG: << parameters.db >>
  coverage:
    executor: gem
    steps:
      - dependencies
      - simplecov

workflows:
  integration-workflow:
    jobs:
      - build
      - linter:
          requires:
            - build
      - specs:
          name: postgres-specs
          db: postgresql
          executor: postgresql
          requires:
            - build
      - specs:
          name: sqlite-specs
          db: sqlite
          executor: gem
          requires:
            - build
      - coverage:
          requires:
            - sqlite-specs